[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]
aptPkgs = ["libatomic1"]

[phases.install]
cmds = ["composer install --no-dev --no-interaction --prefer-dist", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && vendor/bin/heroku-php-apache2 public/"
